---
# copyright Utrecht University

# I-lab Catalog configuration
ilab_catalog_version: development          # I-lab Catalog version to install
ilab_catalog_fqdn: ilab-catalog.ckan.test  # I-lab Catalog fully qualified domain name (FQDN)

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_key_signed: localhost.key
openssl_crt_signed: localhost.crt

# CKAN Database settings
ckan_db_encoding: UTF-8
ckan_db_lc_collate: en_US.utf8
ckan_db_lc_ctype: en_US.utf8

# CKAN extension verions
ckanext_harvest_version: 7dd82a0e01ba85b7f2f4cc02b66dd4948ed7093e
ckanext_oaipmh_version: '{{ ilab_catalog_version }}'
ckanext_custom_theme_version: '{{ ilab_catalog_version }}'
