---
# copyright Utrecht University

- name: Ensure CKAN prerequisites are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - python3-devel
    - python3-pip
    - python3-virtualenv
    - python3-mod_wsgi
    - postgresql-devel
    - httpd-devel
    - unzip


- name: Ensure a 'wheel' group exists
  group:
    name: wheel
    state: present


- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s


- name: Ensure CKAN user exists
  user:
    name: ckan
    comment: "CKAN User"
    home: /usr/lib/ckan
    shell: /bin/bash
    groups: wheel
    append: yes


- name: Ensure CKAN database exists
  become_user: postgres
  become: yes
  postgresql_db:
    name: "ckan_default"
    encoding: "{{ ckan_db_encoding }}"
    lc_collate: "{{ ckan_db_lc_collate }}"
    lc_ctype: "{{ ckan_db_lc_ctype }}"
    template: template0


- name: Ensure CKAN database user exists
  become_user: postgres
  become: yes
  postgresql_user:
    db: "ckan_default"
    name: "ckan_default"
    password: "{{ ckan_database_password }}"
    priv: ALL


- name: Allow Apache to connect to Postgresql
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes


- name: Allow Apache to connect to Redis and SOLR
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes


- name: Allow Apache to listen on port 8983 for Solr
  seport:
    ports: 8888
    proto: tcp
    setype: http_port_t
    state: present


- name: Ensure CKAN directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: ckan
  with_items:
    - /usr/lib/ckan
    - /usr/lib/ckan/default
    - /etc/ckan
    - /etc/ckan/default


- name: Run CKAN installation script
  become_user: ckan
  shell: |
    python3 -m venv /usr/lib/ckan/default
    . /usr/lib/ckan/default/bin/activate
    python3 -m pip install setuptools==44.1.0
    python3 -m pip install --upgrade pip
    python3 -m pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.9.0#egg=ckan[requirements]'
    python3 -m pip install --ignore-installed -r /usr/lib/ckan/default/src/ckan/pip-requirements-docs.txt
    deactivate
  args:
    creates: /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml
  register: ckan_installed


- name: Generate session secret
  shell: openssl rand -base64 32 > /etc/ckan/default/session_secret
    creates=/etc/ckan/default/session_secret
  when: not ansible_check_mode


- name: Read session secret
  command: cat /etc/ckan/default/session_secret
  register: session_secret
  check_mode: no
  changed_when: false


- name: Generate unique application instance identifier
  shell: 'echo {{ ansible_hostname | to_uuid }} > /etc/ckan/default/app_instance_uuid
    creates=/etc/ckan/default/app_instance_uuid'
  when: not ansible_check_mode


- name: Read unique application instance identifier
  command: cat /etc/ckan/default/app_instance_uuid
  register: app_instance_uuid
  check_mode: no
  changed_when: false


- name: Ensure CKAN config is present
  template:
    src: "ckan.ini.j2"
    dest: "/etc/ckan/default/ckan.ini"
  notify: Restart Apache webserver


- name: Ensure CKAN schema is symlinked in Solr
  become_user: root
  become: yes
  file:
    src: /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml
    dest: /var/solr/data/ckan/conf/schema.xml
    state: link
  register: link_schema
  notify: Restart Solr


- name: Ensure CKAN who.ini is symlinked
  become_user: root
  become: yes
  file:
    src: /usr/lib/ckan/default/src/ckan/who.ini
    dest: /etc/ckan/default/who.ini
    state: link


- name: Install CKAN harvest extension
  become_user: root
  become: yes
  shell: |
    su -s /bin/bash - ckan
    cd /usr/lib/ckan
    . default/bin/activate
    python3 -m pip install -e git+https://github.com/ckan/ckanext-harvest.git@{{ ckanext_harvest_version }}#egg=ckanext-harvest
    cd /usr/lib/ckan/default/src/ckanext-harvest/
    python3 -m pip install -r pip-requirements.txt
    deactivate
    exit
    creates=/usr/lib/ckan/default/src/ckanext-harvest/
  notify: Restart Apache webserver


- name: Ensure latest version of CKAN harvest extension is installed
  become_user: root
  become: yes
  git:
    repo: "https://github.com/ckan/ckanext-harvest.git"
    dest: "/usr/lib/ckan/default/src/ckanext-harvest/"
    version: "{{ ckanext_harvest_version }}"
    update: "yes"
  notify: Restart Apache webserver


- name: Install CKAN OAI-PMH extension
  become_user: root
  become: yes
  shell: |
    su -s /bin/bash - ckan
    cd /usr/lib/ckan
    . default/bin/activate
    python3 -m pip install -e git+https://github.com/UtrechtUniversity/ckanext-oaipmh.git@{{ ckanext_oaipmh_version }}#egg=ckanext-oaipmh
    cd /usr/lib/ckan/default/src/ckanext-oaipmh/
    python3 -m pip install -r requirements.txt
    python setup.py develop
    deactivate
    exit
    creates=/usr/lib/ckan/default/src/ckanext-oaipmh/
  notify: Restart Apache webserver


- name: Ensure latest version of CKAN OAI-PMH extension is installed
  become_user: root
  become: yes
  git:
    repo: "https://github.com/UtrechtUniversity/ckanext-oaipmh.git"
    dest: "/usr/lib/ckan/default/src/ckanext-oaipmh"
    version: "{{ ckanext_oaipmh_version }}"
    update: "yes"
  notify: Restart Apache webserver


- name: Install Yoda Catalog custom CKAN theme
  become_user: root
  become: yes
  shell: |
    su -s /bin/bash - ckan
    cd /usr/lib/ckan
    . default/bin/activate
    python3 -m pip install -e git+https://github.com/UtrechtUniversity/ilab-catalog-theme.git@{{ ckanext_custom_theme_version }}#egg=ckanext-custom_theme
    deactivate
    exit
    creates=/usr/lib/ckan/default/src/ckanext-custom-theme/
  notify: Restart Apache webserver


- name: Ensure latest version of Yoda Catalog custom CKAN theme is installed
  become_user: root
  become: yes
  git:
    repo: "https://github.com/UtrechtUniversity/ilab-catalog-theme.git"
    dest: "/usr/lib/ckan/default/src/ckanext-custom-theme/"
    version: "{{ ckanext_custom_theme_version }}"
    update: "yes"


- name: Initialize CKAN database
  become_user: ckan
  become: yes
  shell: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    ckan -c /etc/ckan/default/ckan.ini db init
    deactivate
    exit
  when: ckan_installed.changed


- name: Check if CKAN admin user exists
  become_user: ckan
  become: yes
  shell: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    ckan -c /etc/ckan/default/ckan.ini user list
    deactivate
    exit
  changed_when: False
  register: ckan_admin_user


- name: Add CKAN admin user
  become_user: ckan
  become: yes
  shell: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    ckan  -c /etc/ckan/default/ckan.ini user add ckanadmin password="{{ ckan_admin_password }}" email=ckanadmin@localhost name=ckanadmin
    ckan -c /etc/ckan/default/ckan.ini sysadmin add ckanadmin
    deactivate
    exit
  when: not "name=ckanadmin" in ckan_admin_user.stdout and not ansible_check_mode


- name: Check if CKAN harvest user exists
  become_user: ckan
  become: yes
  shell: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    ckan -c /etc/ckan/default/ckan.ini user list
    deactivate
    exit
  changed_when: False
  register: ckan_harvest_user


- name: Add CKAN harvest user
  become_user: ckan
  become: yes
  shell: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    . /usr/lib/ckan/default/bin/activate
    cd /usr/lib/ckan/default/src/ckan
    ckan -c /etc/ckan/default/ckan.ini user add harvest password="{{ ckan_harvest_password }}" email=harvest@localhost name=harvest
    ckan -c /etc/ckan/default/ckan.ini sysadmin add harvest
    deactivate
    exit
  when: not "name=harvest" in ckan_admin_user.stdout and not ansible_check_mode


- name: Ensure WSGI script file for CKAN is present
  template:
    src: "apache.wsgi.j2"
    dest: "/etc/ckan/default/apache.wsgi"
  notify: Restart Apache webserver


- name: Ensure UU Catalog virtual host config for Apache is present
  template:
    src: "uu-catalog-vhost.conf.j2"
    dest: "/etc/httpd/conf.d/uu-catalog-vhost.conf"
  notify: Restart Apache webserver
