---
# copyright Utrecht University
# This playbook deploys a complete Yoda Catalog CKAN instance.

- hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to deploy Yoda Catalog CKAN."


- name: Provision Yoda Catalog CKAN server
  hosts: all
  become: yes
  roles:
    - common
    - certificates
    - apache
    - postgresql
    - solr
    - redis
    - ckan
    - ckan-harvester
