---
# copyright Utrecht University
# This playbook provisions Yoda Catalog CKAN instance with the Zabbix agent, PostgreSQL monitoring and Zabbix user access to the database.

- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to deploy Yoda Catalog CKAN."


- name: Provision Yoda Catalog CKAN server with Zabbix monitoring
  hosts: all
  become: true
  roles:
    - zabbix-agent
    - role: zabbix-postgresql
      zabbix_database_name: "{{ ckan_database_name }}"
    - zabbix-ckan
