---
# copyright Utrecht University

- name: Ensure Supervisor is installed
  ansible.builtin.package:
    name: supervisor
    state: present


- name: Ensure Supervisor configuration for CKAN harvesting is present
  ansible.builtin.template:
    src: "ckan_harvesting.ini.j2"
    dest: "/etc/supervisord.d/ckan_harvesting.ini"
    owner: root
    group: root
    mode: '0644'

- name: Ensure CKAN log directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ckan
  with_items:
    - /var/log/ckan
    - /var/log/ckan/std


- name: Ensure Supervisor is started and enabled on boot
  ansible.builtin.service:
    name: supervisord
    state: started
    enabled: true


- name: Add Supervisor ckan_gather_consumer task
  community.general.supervisorctl:
    name: ckan_gather_consumer
    state: present


- name: Add Supervisor ckan_fetch_consumer task
  community.general.supervisorctl:
    name: ckan_fetch_consumer
    state: present


- name: Configure harvester cronjob
  become_user: ckan
  become: true
  ansible.builtin.cron:
    name: ckan_harvester
    minute: '*/2'
    hour: '*'
    day: '*'
    job: /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini harvester run
