---
# copyright Utrecht University

- name: Restart Supervisorctl
  ansible.builtin.service:
    name: supervisorctl
    state: restarted


# Using command instead of supervisorctl module because of limitations in supervisorctl
# module regarding ordering of operations and not having a reload operation.
- name: Supervisor reload and restart all
  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: |
      supervisorctl reload
      supervisorctl restart all
