---
# copyright Utrecht University

- name: Ensure Ansible dependencies are installed (EL 7)
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - libsemanage-python
    - libselinux-python
    - policycoreutils-python
    - python2-cryptography
  when: ansible_distribution_major_version == "7"


- name: Ensure Ansible dependencies are installed (EL 8)
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - policycoreutils-python-utils
    - python3-libselinux
  when: ansible_distribution_major_version == "8"


- name: Ensure basics (vim, bind-utils, etc.) are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - bind-utils
    - vim
    - htop
    - git
    - tmux
