---
# copyright Utrecht University

- name: Ensure Ansible dependencies are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - libsemanage-python
    - libselinux-python
    - policycoreutils-python
    - python2-cryptography


- name: Ensure basics (vim, bind-utils, etc.) are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - bind-utils
    - vim
    - htop
    - git
    - tmux
