---
# copyright Utrecht University

- name: Ensure Ansible dependencies are installed
  package:
    name: policycoreutils-python-utils
    state: present


- name: Ensure basics (vim, bind-utils, etc.) are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - bind-utils
    - vim
    - htop
    - nmon
    - git
    - tmux
