---
# copyright Utrecht University

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_key_signed: localhost.key
openssl_crt_signed: localhost.crt

# There is also a default value for PostgreSQL version in the CKAN role
postgresql_version: 15
