---
# copyright Utrecht University

- name: Check if Zabbix PostgreSQL monitoring RPM is installable from repository
  ansible.builtin.yum:
    list: '{{ zabbix_postgres.package }}'
  register: zabbix_postgres_repo


- name: Download Zabbix PostgreSQL monitoring RPM
  ansible.builtin.get_url:
    url: '{{ zabbix_postgres.url }}/{{ zabbix_postgres.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ zabbix_postgres.filename }}'
    checksum: '{{ zabbix_postgres.checksum }}'
    owner: root
    group: root
    mode: "0644"
  when: not zabbix_postgres_repo.results and not repo_only
  notify: Restart Zabbix agent


- name: Install Zabbix PostgreSQL monitoring from downloaded RPM (EL7)
  ansible.builtin.package:
    name: '{{ rpm_dest_dir }}/{{ zabbix_postgres.filename }}'
    state: present
  when: not zabbix_postgres_repo.results and not repo_only and ansible_distribution_major_version == "7"


- name: Install Zabbix PostgreSQL monitoring from downloaded RPM (EL8)
  ansible.builtin.yum:
    name: '{{ rpm_dest_dir }}/{{ zabbix_postgres.filename }}'
    state: present
    disable_gpg_check: true
  when: not zabbix_postgres_repo.results and not repo_only and ansible_distribution_major_version == "8"


- name: Ensure Zabbix PostgreSQL monitoring RPM is installed
  ansible.builtin.package:
    name: '{{ zabbix_postgres.package }}'
    state: present
  when: zabbix_postgres_repo.results
  notify: Restart Zabbix agent


- name: Create Zabbix database user
  become_user: postgres
  become: true
  community.general.postgresql_user:
    db: "{{ zabbix_database_name }}"
    name: "{{ zabbix_database_user }}"
    priv: "CONNECT"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
